// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace True.Services.HubSpot.Tickets.Models {
    /// <summary>null</summary>
    public enum Filter_operator {
        [EnumMember(Value = "EQ")]
        EQ,
        [EnumMember(Value = "NEQ")]
        NEQ,
        [EnumMember(Value = "LT")]
        LT,
        [EnumMember(Value = "LTE")]
        LTE,
        [EnumMember(Value = "GT")]
        GT,
        [EnumMember(Value = "GTE")]
        GTE,
        [EnumMember(Value = "BETWEEN")]
        BETWEEN,
        [EnumMember(Value = "IN")]
        IN,
        [EnumMember(Value = "NOT_IN")]
        NOT_IN,
        [EnumMember(Value = "HAS_PROPERTY")]
        HAS_PROPERTY,
        [EnumMember(Value = "NOT_HAS_PROPERTY")]
        NOT_HAS_PROPERTY,
        [EnumMember(Value = "CONTAINS_TOKEN")]
        CONTAINS_TOKEN,
        [EnumMember(Value = "NOT_CONTAINS_TOKEN")]
        NOT_CONTAINS_TOKEN,
    }
}
