// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using True.Services.HubSpot.Properties.Crm.V3.Properties.Item;
namespace True.Services.HubSpot.Properties.Crm.V3.Properties {
    /// <summary>
    /// Builds and executes requests for operations under \crm\v3\properties
    /// </summary>
    public class PropertiesRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the True.Services.HubSpot.Properties.crm.v3.properties.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithObjectTypeItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("objectType", position);
            return new WithObjectTypeItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new PropertiesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/v3/properties", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new PropertiesRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/crm/v3/properties", rawUrl) {
        }
    }
}
