// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace True.Services.HubSpot.Pipelines.Models {
    public enum PipelineStage_writePermissions {
        [EnumMember(Value = "CRM_PERMISSIONS_ENFORCEMENT")]
        CRM_PERMISSIONS_ENFORCEMENT,
        [EnumMember(Value = "READ_ONLY")]
        READ_ONLY,
        [EnumMember(Value = "INTERNAL_ONLY")]
        INTERNAL_ONLY,
    }
}
