// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace True.Services.HubSpot.Properties.Models {
    public enum BatchResponseProperty_status {
        [EnumMember(Value = "PENDING")]
        PENDING,
        [EnumMember(Value = "PROCESSING")]
        PROCESSING,
        [EnumMember(Value = "CANCELED")]
        CANCELED,
        [EnumMember(Value = "COMPLETE")]
        COMPLETE,
    }
}
