// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace True.Services.HubSpot.Properties.Models {
    /// <summary>Controls how the property appears in HubSpot.</summary>
    public enum PropertyUpdate_fieldType {
        [EnumMember(Value = "textarea")]
        Textarea,
        [EnumMember(Value = "text")]
        Text,
        [EnumMember(Value = "date")]
        Date,
        [EnumMember(Value = "file")]
        File,
        [EnumMember(Value = "number")]
        Number,
        [EnumMember(Value = "select")]
        Select,
        [EnumMember(Value = "radio")]
        Radio,
        [EnumMember(Value = "checkbox")]
        Checkbox,
        [EnumMember(Value = "booleancheckbox")]
        Booleancheckbox,
        [EnumMember(Value = "calculation_equation")]
        Calculation_equation,
    }
}
