// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace True.Services.HubSpot.Properties.Models {
    /// <summary>The data type of the property.</summary>
    public enum PropertyUpdate_type {
        [EnumMember(Value = "string")]
        String,
        [EnumMember(Value = "number")]
        Number,
        [EnumMember(Value = "date")]
        Date,
        [EnumMember(Value = "datetime")]
        Datetime,
        [EnumMember(Value = "enumeration")]
        Enumeration,
        [EnumMember(Value = "bool")]
        Bool,
    }
}
